name: 'Publish'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --frozen-lockfile

      - run: yarn test

      - run: yarn build

      - name: Set Git credentials
        run: |
          git config user.email "github-action@users.noreply.github.com"
          git config user.name "GitHub Action"

      - run: yarn version --new-version ${{ github.event.inputs.version }} --no-commit-hooks

      - name: Publushing release
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_PUBLISH_TOKEN }}

      - name: Pushing changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}
          branch: ${{ github.ref }}
